<a href="https://colab.research.google.com/github/arctenis/numpy_tutorial/blob/main/numpy00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


revenus = [1200, 2000, 1800, 3200, 4500]
revenus_array = np.array(revenus)
print(f"revenus_array : {revenus_array}")

print(f"moyenne : {np.mean(revenus_array)}")

print(f"np.zeros(5) : {np.zeros(5)}")
print(f"np.arange(1, 12, 3) : {np.arange(1, 12, 3)}")
print(f"np.linspace(1, 12, 3) : {np.linspace(1, 12, 3)}")
print(f"revenus_array.dtype : {revenus_array.dtype}")


revenus_array : [1200 2000 1800 3200 4500]
moyenne : 2540.0
np.zeros(5) : [0. 0. 0. 0. 0.]
np.arange(1, 12, 3) : [ 1  4  7 10]
np.linspace(1, 12, 3) : [ 1.   6.5 12. ]
revenus_array.dtype : int64
[1200 1800]


Ajouter des conditions pour créer un autre _array_.

In [ ]:
revenus_array[(revenus_array > 1000) & (revenus_array < 2000)]

array([1200, 1800])

In [ ]:
revenus_array.mean()

2540.0

In [ ]:
np.median(revenus_array)

2000.0

## N dimensions


In [ ]:
np.ones((5, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((8, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.random((4, 2))

array([[0.0374575 , 0.07891188],
       [0.64661962, 0.8324498 ],
       [0.91459142, 0.78014782],
       [0.39033644, 0.84992238]])

In [ ]:
np.random.randint(1, 6, size=(6, 6))

array([[4, 4, 2, 4, 3, 5],
       [2, 2, 5, 2, 1, 3],
       [3, 5, 5, 3, 2, 3],
       [1, 2, 2, 2, 3, 4],
       [3, 4, 2, 2, 3, 3],
       [5, 3, 2, 5, 2, 5]])

In [ ]:
a = np.linspace(5, 10, 11)
print(a)

print(a[-3:-1])

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
[9.  9.5]


In [ ]:
b = np.array([[[1, 2],[4, 5]],

        [[6, 7],[8, 9]],

        [[10, 11],[12, 13]]])
display(b.shape)
display(b[2, :, :])

(3, 2, 2)

array([[10, 11],
       [12, 13]])